### ISSUE TITLE
Can you add the meta charset so Spanish users can write in their language? They want to use Spanish accents

<meta charset="UTF-8" />

### ISSUE THREAD

**Issue by Raoden4Elantris** [beager/ebtext#9]

**Comment by beager** [comment]
Hi @Raoden4Elantris. I think I understand the request here, and I'll explain what could be done vs. what may not be possible here.

- Your use case is to support generating Latin character-based texts with diacritics to support Spanish (or other languages that use Latin diacritics) texts through the generator. This would mean that generated texts would include those diacritics (á, é, í, ó, ú, ü, ñ).
- The issue with supporting diacritics is that the [sprite sheet](https://github.com/beager/ebtext/blob/master/assets/text/plain.png) for EarthBound's text does not contain any letters with diacritics. It does contain some Japanese, which could be mapped in, but unfortunately no Latin letters with diacritics.
- There are bootleg PAL versions of EarthBound, and ROM hacks for Spanish translations of EarthBound, but I don't have access to them and the work to retrofit any characters from those things into this generator seems too arduous.
- There could be a library added that will take diacritics and map them to the appropriate mapped character, but this would result in generated Spanish or other Latin-based texts missing their diacritics (e.g. "Escribiré más código mañana" would become "Escribire mas codigo manana").
- If there is a clean plain and flavored sprite sheet for diacritics, it could be proposed as a PR and I can consider mapping it in, but I cannot guarantee a timeline for it.

Happy to hear your thoughts!

**Comment by Raoden4Elantris** [comment]
Hi. I see what's the problem. I requested to you just because a friend of
mine wanted to use diacritics in his texts, I'll say him your answer.
Thanks anyways
